# initial setting
spring.application.name=LuckyPawsBackend
server.port=${SERVER_PORT:50023}
server.address=${SERVER_ADDRESS:10.240.111.191}

# dblink info
#system parameters :// SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate) setting: automatically table create&update
# `update` ??? ???? ??? ???, ?? ??? ??? ???????.
spring.jpa.hibernate.ddl-auto=update

# SQL query (to see console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true