# ============================================
# ?????? ??
# ============================================
spring.application.name=LuckyPawsBackend
server.address=0.0.0.0
# server.port=50023

# ============================================
# ??? H2 ?????? ??
# ============================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true


# Hibernate + DDL ?? (?? ??? ??/????)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ???? SQL ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 ?? (/h2-console ???? ?? ??)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ============================================
# (??? MySQL ?? - ??? ?? ??)
# ============================================
# spring.datasource.url=jdbc:mysql://127.0.0.1:3306/your_db?useSSL=false&serverTimezone=Asia/Seoul
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
